import icon from "./icon.png";
import blog from "./blog.png";
import board from "./board.png";
import burgerBuilder from "./burger-builder.png";
import htmlTableCreator from "./html-table-creator.png";
import slack from "./slack.png";
import atcoder from "./atcoder.png";
import cookle from "./cookle.png";
import slimline from "./slimline.png";
export { icon, blog, board, burgerBuilder, htmlTableCreator, slack, atcoder, cookle, slimline };
