name: check diff in bun lockfile

on:
  push:
    paths:
      - "bun.lockb"
    branches-ignore:
      - main

jobs:
  diff-check:
    name: diff check bun lockfile
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.25.2
      - name: Setup for lockfile diff
        run: |
          git config core.attributesFile .gitattributes && echo "bun.lockb diff=lockb" >> .gitattributes
          git config diff.lockb.textconv bun
          git config diff.lockb.binary true
      - uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
      - name: Check diff in bun lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          github-comment hide -k bun_diff
          github-comment exec -k bun_diff -- git diff origin/main HEAD -- bun.lockb
