name: Check diff in bun lockfile

on:
  push:
    paths:
      - 'bun.lockb'
    branches-ignore:
      - main

jobs:
  diff-check:
    name: diff check bun lockfile
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.25.2
      - name: Setup for lockfile diff
        run: |
          git config core.attributesFile .gitattributes && echo "bun.lockb diff=lockb" >> .gitattributes
          git config diff.lockb.textconv bun
          git config diff.lockb.binary true
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
      - name: Check diff in bun lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          github-comment hide -k bun_diff
          github-comment exec -k bun_diff -- git diff origin/main HEAD -- bun.lockb
