name: test
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - args: ["--frozen-lockfile"]
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
