name: Update GitHub Actions comment
on: pull_request

jobs:
  update-github-actinos-comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      pull-requests: write
    if: ${{ github.actor == 'renovate[bot]' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: aquaproj/aqua-installer@e6160e5a751bbcbd337a834eb75c15ba9ca206ae # v3.0.2
        with:
          aqua_version: v2.25.2
      - run: pinact run
      - name: Check pinact diff
        id: pinact
        continue-on-error: true
        run: git diff --exit-code .github
      - uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        if: steps.pinact.outcome != 'success'
        with:
          commit-message: "chore: Update github actions comment"
          branch: ${{ github.ref_name }}/propose-generated-diff
          base: ${{ github.event.pull_request.head.ref }}
          delete-branch: true
          title: "chore: Update github actions comment"
          body: "refs. #${{ github.event.number }}"
          token: ${{ secrets.WORKFLOW_TOKEN }}
